---
# CloudFormation Stack for Tor Metrics Operational Monitoring
# This stack will only deploy on us-east-1 and will deploy in its own VPC there
# aws cloudformation deploy --region us-east-1 --stack-name metrics-monitor --template-file metrics-monitor.yml --capabilities CAPABILITY_IAM
AWSTemplateFormatVersion: 2010-09-09
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref VPC
      CidrBlock: 172.31.0.0/20
      MapPublicIpOnLaunch: true
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet
  InternetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Internet Security Group"
      GroupDescription: "SSH traffic in, all traffic out."
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  PingableSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Pingable Security Group"
      GroupDescription: "ICMP echo requests in"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
  MonitorInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0bd9223868b4778d7
      InstanceType: t2.micro
      SubnetId: !Ref Subnet
      IamInstanceProfile: !Ref AlerterInstanceProfile
      KeyName: "irl yubikey 4"
      SecurityGroupIds:
        - !Ref InternetSecurityGroup
        - !Ref PingableSecurityGroup
  AlertContact:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "MetricsAlertNotification"
      Subscription:
        - Endpoint: "irl@torproject.org"
          Protocol: email
  AlerterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref AlerterRole
  AlerterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: |
        {
          "Version":"2012-10-17",
          "Statement":[{
            "Effect":"Allow",
            "Principal": {
              "Service": ["ec2.amazonaws.com"]
            },
            "Action": "sts:AssumeRole"
          }]
        }
  AlerterPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AlertPublishPolicy
      PolicyDocument:
        Statement:
          - Action: sns:Publish
            Effect: Allow
            Resource: !Ref AlertContact
        Version: '2012-10-17'
      Roles:
      - !Ref AlerterRole
