---
# CloudFormation Stack for OnionPerf development instance
# This stack will only deploy on us-east-1 and will deploy in its own VPC there
# TODO: Generalise the SSH key to use
# aws cloudformation deploy --region us-east-1 --stack-name `whoami`-onionperf-dev --template-file onionperf-dev.yml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0bd9223868b4778d7
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue: !Sub 'MetricsSubnet'
      KeyName: "irl yubikey 4"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub 'MetricsInternetSecurityGroup'
        - Fn::ImportValue: !Sub 'MetricsPingableSecurityGroup'
        - Fn::ImportValue: !Sub 'MetricsHTTPSecurityGroup'
        - Fn::ImportValue: !Sub 'MetricsHTTPSSecurityGroup'
Outputs:
  PublicIp:
    Description: "Instance public IP"
    Value: !GetAtt Instance.PublicIp
