---
# CloudFormation Stack for OnionPerf development instance
# This stack will only deploy on us-east-1 and will deploy in the Metrics VPC
# aws cloudformation deploy --region us-east-1 --stack-name `whoami`-onionperf-dev  --parameter-overrides myKeyPair="$(./identify_user.sh)" --template-file onionperf-dev.yml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  myKeyPair:
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-01db78123b2b99496
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue: !Sub 'MetricsSubnet'
      KeyName:
        Ref: myKeyPair
      SecurityGroupIds:
        - Fn::ImportValue: !Sub 'MetricsInternetSecurityGroup'
        - Fn::ImportValue: !Sub 'MetricsPingableSecurityGroup'
        - Fn::ImportValue: !Sub 'MetricsHTTPSecurityGroup'
        - Fn::ImportValue: !Sub 'MetricsHTTPSSecurityGroup'
  OnionperfDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: onionperf-dev.torproject.net.
      Name: !Join ['', [!Ref 'AWS::StackName', .onionperf-dev.torproject.net.]]
      Type: A
      TTL: '300'
      ResourceRecords:
      - !GetAtt Instance.PublicIp
Outputs:
  PublicIp:
    Description: "Instance public IP"
    Value: !GetAtt Instance.PublicIp
