---
- name: Copy Apache default configuration
  template:
    src: files/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: www-data
    group: www-data
    mode: '0644'
  become: true

- name: Copy Apache SSL configuration
  template:
    src: files/default-ssl.conf.j2
    dest: /etc/apache2/sites-available/default-ssl.conf
    owner: www-data
    group: www-data
    mode: '0644'
  become: true
- name: Enable SSL module
  apache2_module:
    state: present
    name: ssl
  become: true
  notify:
    - reload apache2

- name: Look for existing SSL website
  stat:
    path: "/etc/apache2/sites-enabled/default-ssl.conf"
  register: ssl_website
  become: true
  run_once: true

- name: Enable SSL website
  command: a2ensite default-ssl.conf
  become: true
  run_once: true
  when: not ssl_website.stat.exists
  notify:
    - reload apache2
