---
- name: disable system tor
  systemd:
    name: tor.service
    enabled: false
    state: stopped
  become: true
- name: install stem from backports
  apt:
    pkg: python-stem
    state: latest
    default_release: buster-backports
  become: true
  notify: restart onionperf
- name: install onionperf dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - git
    - libglib2.0-0
    - libigraph0v5
    - python-ipaddress
    - python-lxml
    - python-matplotlib
    - python-netifaces
    - python-networkx
    - python-nose
    - python-numpy
    - python-scipy
  become: true
  notify: restart onionperf
- name: clone onionperf repository
  git:
    repo: 'https://git.torproject.org/onionperf.git'
    dest: /srv/checkout
  become: true
  register: opchange
- name: clone tgen repository
  git:
    repo: 'https://github.com/shadow/tgen.git'
    dest: /srv/checkout
  become: true
  register: tgenchange
- name: create onionperf user
  user:
    name: onionperf
    state: present
    comment: OnionPerf Service User
    home: /srv/onionperf.torproject.net
  become: true
- name: install onionperf service file
  template:
    src: files/onionperf.service.j2
    dest: /etc/systemd/system/onionperf.service
  notify: restart onionperf
  become: true
- name: install apache2
  apt:
    name: apache2
  become: true

